spring:
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s273720
    password: UDU8hfjQjziKasms

#    For local testing.
#    url: jdbc:postgresql://localhost:5432/soa
#    username: postgres
#    password: 123456

server:
  port: 8080
#  ssl:
#    key-store: src/main/resources/server.keystore
#    key-store-password: helios
#    keyStoreType: PKCS12
#    keyAlias: tomcat